// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: sharedisk/v1/local.proto

package sharediskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImportRequest requests a file to be imported into the managed object area.
type ImportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path of the source file.
	SourcePath string `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	// Target folder ID in the logical directory.
	FolderId string `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// Display name for the file entry.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRequest) Reset() {
	*x = ImportRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRequest) ProtoMessage() {}

func (x *ImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRequest.ProtoReflect.Descriptor instead.
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{0}
}

func (x *ImportRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ImportRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *ImportRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ImportResponse contains the result of an import operation.
type ImportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the created file entry.
	FileEntryId string `protobuf:"bytes,1,opt,name=file_entry_id,json=fileEntryId,proto3" json:"file_entry_id,omitempty"`
	// ID of the file object.
	FileObjectId string `protobuf:"bytes,2,opt,name=file_object_id,json=fileObjectId,proto3" json:"file_object_id,omitempty"`
	// SHA-256 hash of the imported file.
	Sha256 []byte `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Size of the imported file in bytes.
	Size          uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResponse) Reset() {
	*x = ImportResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResponse) ProtoMessage() {}

func (x *ImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResponse.ProtoReflect.Descriptor instead.
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{1}
}

func (x *ImportResponse) GetFileEntryId() string {
	if x != nil {
		return x.FileEntryId
	}
	return ""
}

func (x *ImportResponse) GetFileObjectId() string {
	if x != nil {
		return x.FileObjectId
	}
	return ""
}

func (x *ImportResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ImportResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// StatRequest requests information about a file or object.
type StatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File entry ID or logical path.
	Identifier    string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{2}
}

func (x *StatRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

// StatResponse contains file/object information.
type StatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File entry information.
	Entry *FileEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	// File object information.
	Object *FileObject `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	// Replica information.
	Replicas      []*Replica `protobuf:"bytes,3,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{3}
}

func (x *StatResponse) GetEntry() *FileEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *StatResponse) GetObject() *FileObject {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *StatResponse) GetReplicas() []*Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

// FileEntry represents a logical file entry in the directory.
type FileEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FolderId       string                 `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ObjectId       string                 `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	OriginDeviceId string                 `protobuf:"bytes,5,opt,name=origin_device_id,json=originDeviceId,proto3" json:"origin_device_id,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Version        int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{4}
}

func (x *FileEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileEntry) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *FileEntry) GetOriginDeviceId() string {
	if x != nil {
		return x.OriginDeviceId
	}
	return ""
}

func (x *FileEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileEntry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FileEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FileEntry) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// FileObject represents a content-addressed file object.
type FileObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mime          string                 `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`
	ChunkSize     uint32                 `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,6,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileObject) Reset() {
	*x = FileObject{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileObject) ProtoMessage() {}

func (x *FileObject) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileObject.ProtoReflect.Descriptor instead.
func (*FileObject) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{5}
}

func (x *FileObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileObject) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *FileObject) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileObject) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *FileObject) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *FileObject) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *FileObject) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Replica represents a replica of a file object on a device.
type Replica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Size          uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	VerifiedAt    string                 `protobuf:"bytes,6,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	ReportedAt    string                 `protobuf:"bytes,7,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	Version       int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replica) Reset() {
	*x = Replica{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replica) ProtoMessage() {}

func (x *Replica) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replica.ProtoReflect.Descriptor instead.
func (*Replica) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{6}
}

func (x *Replica) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Replica) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Replica) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Replica) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Replica) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Replica) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

func (x *Replica) GetReportedAt() string {
	if x != nil {
		return x.ReportedAt
	}
	return ""
}

func (x *Replica) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// VerifyRequest requests verification of a local object.
type VerifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Object ID to verify.
	ObjectId      string `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

// VerifyResponse contains the verification result.
type VerifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the object is valid.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Actual SHA-256 hash (if different from expected).
	ActualSha256 []byte `protobuf:"bytes,2,opt,name=actual_sha256,json=actualSha256,proto3" json:"actual_sha256,omitempty"`
	// Error message if verification failed.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResponse) GetActualSha256() []byte {
	if x != nil {
		return x.ActualSha256
	}
	return nil
}

func (x *VerifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StatusRequest requests the current agent status.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{9}
}

// StatusResponse contains the agent status.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent version.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Device ID.
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Storage root path.
	StorageRoot string `protobuf:"bytes,3,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	// Number of local objects.
	ObjectCount int64 `protobuf:"varint,4,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`
	// Total storage used in bytes.
	StorageUsed uint64 `protobuf:"varint,5,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	// Available storage in bytes.
	StorageAvailable uint64 `protobuf:"varint,6,opt,name=storage_available,json=storageAvailable,proto3" json:"storage_available,omitempty"`
	// Active transfers.
	ActiveTransfers int32 `protobuf:"varint,7,opt,name=active_transfers,json=activeTransfers,proto3" json:"active_transfers,omitempty"`
	// Last sync sequence number.
	LastSyncSeq   int64 `protobuf:"varint,8,opt,name=last_sync_seq,json=lastSyncSeq,proto3" json:"last_sync_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StatusResponse) GetStorageRoot() string {
	if x != nil {
		return x.StorageRoot
	}
	return ""
}

func (x *StatusResponse) GetObjectCount() int64 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

func (x *StatusResponse) GetStorageUsed() uint64 {
	if x != nil {
		return x.StorageUsed
	}
	return 0
}

func (x *StatusResponse) GetStorageAvailable() uint64 {
	if x != nil {
		return x.StorageAvailable
	}
	return 0
}

func (x *StatusResponse) GetActiveTransfers() int32 {
	if x != nil {
		return x.ActiveTransfers
	}
	return 0
}

func (x *StatusResponse) GetLastSyncSeq() int64 {
	if x != nil {
		return x.LastSyncSeq
	}
	return 0
}

// ListTransfersRequest requests a list of transfers.
type ListTransfersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by status (empty means all).
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Maximum number of results.
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Cursor for pagination.
	Cursor        string `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersRequest) Reset() {
	*x = ListTransfersRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersRequest) ProtoMessage() {}

func (x *ListTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersRequest.ProtoReflect.Descriptor instead.
func (*ListTransfersRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{11}
}

func (x *ListTransfersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTransfersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTransfersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// ListTransfersResponse contains a list of transfers.
type ListTransfersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of transfers.
	Transfers []*Transfer `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	// Cursor for next page.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersResponse) Reset() {
	*x = ListTransfersResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersResponse) ProtoMessage() {}

func (x *ListTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersResponse.ProtoReflect.Descriptor instead.
func (*ListTransfersResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{12}
}

func (x *ListTransfersResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *ListTransfersResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// Transfer represents a transfer task.
type Transfer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjectId       string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	TargetDeviceId string                 `protobuf:"bytes,3,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	State          string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Priority       int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	LeaseOwner     string                 `protobuf:"bytes,7,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	LeaseUntil     string                 `protobuf:"bytes,8,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"`
	Attempt        int32                  `protobuf:"varint,9,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Version        int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{13}
}

func (x *Transfer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transfer) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Transfer) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

func (x *Transfer) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Transfer) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Transfer) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Transfer) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *Transfer) GetLeaseUntil() string {
	if x != nil {
		return x.LeaseUntil
	}
	return ""
}

func (x *Transfer) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Transfer) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Transfer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transfer) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CancelTransferRequest requests cancellation of a transfer.
type CancelTransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transfer ID to cancel.
	TransferId    string `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransferRequest) Reset() {
	*x = CancelTransferRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferRequest) ProtoMessage() {}

func (x *CancelTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferRequest.ProtoReflect.Descriptor instead.
func (*CancelTransferRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{14}
}

func (x *CancelTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

// CancelTransferResponse contains the result of a cancel operation.
type CancelTransferResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the transfer was canceled.
	Canceled bool `protobuf:"varint,1,opt,name=canceled,proto3" json:"canceled,omitempty"`
	// Error message if cancellation failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransferResponse) Reset() {
	*x = CancelTransferResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferResponse) ProtoMessage() {}

func (x *CancelTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferResponse.ProtoReflect.Descriptor instead.
func (*CancelTransferResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{15}
}

func (x *CancelTransferResponse) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *CancelTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LocalFileRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mime          string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	PurgeAfter    string                 `protobuf:"bytes,8,opt,name=purge_after,json=purgeAfter,proto3" json:"purge_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalFileRecord) Reset() {
	*x = LocalFileRecord{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalFileRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalFileRecord) ProtoMessage() {}

func (x *LocalFileRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalFileRecord.ProtoReflect.Descriptor instead.
func (*LocalFileRecord) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{16}
}

func (x *LocalFileRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocalFileRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalFileRecord) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *LocalFileRecord) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LocalFileRecord) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *LocalFileRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LocalFileRecord) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *LocalFileRecord) GetPurgeAfter() string {
	if x != nil {
		return x.PurgeAfter
	}
	return ""
}

type ListLocalFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trash         bool                   `protobuf:"varint,1,opt,name=trash,proto3" json:"trash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocalFilesRequest) Reset() {
	*x = ListLocalFilesRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocalFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocalFilesRequest) ProtoMessage() {}

func (x *ListLocalFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocalFilesRequest.ProtoReflect.Descriptor instead.
func (*ListLocalFilesRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{17}
}

func (x *ListLocalFilesRequest) GetTrash() bool {
	if x != nil {
		return x.Trash
	}
	return false
}

type ListLocalFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*LocalFileRecord     `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocalFilesResponse) Reset() {
	*x = ListLocalFilesResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocalFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocalFilesResponse) ProtoMessage() {}

func (x *ListLocalFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocalFilesResponse.ProtoReflect.Descriptor instead.
func (*ListLocalFilesResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{18}
}

func (x *ListLocalFilesResponse) GetFiles() []*LocalFileRecord {
	if x != nil {
		return x.Files
	}
	return nil
}

type MutateLocalFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateLocalFileRequest) Reset() {
	*x = MutateLocalFileRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateLocalFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateLocalFileRequest) ProtoMessage() {}

func (x *MutateLocalFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateLocalFileRequest.ProtoReflect.Descriptor instead.
func (*MutateLocalFileRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{19}
}

func (x *MutateLocalFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *MutateLocalFileRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MutateLocalFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MutateLocalFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *LocalFileRecord       `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateLocalFileResponse) Reset() {
	*x = MutateLocalFileResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateLocalFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateLocalFileResponse) ProtoMessage() {}

func (x *MutateLocalFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateLocalFileResponse.ProtoReflect.Descriptor instead.
func (*MutateLocalFileResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{20}
}

func (x *MutateLocalFileResponse) GetFile() *LocalFileRecord {
	if x != nil {
		return x.File
	}
	return nil
}

type ExportRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileId          string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	DestinationPath string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{21}
}

func (x *ExportRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ExportRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

type ExportResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DestinationPath string                 `protobuf:"bytes,1,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	Size            uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256          string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{22}
}

func (x *ExportResponse) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *ExportResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ExportResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type CoordinatorEnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorEnrollRequest) Reset() {
	*x = CoordinatorEnrollRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorEnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorEnrollRequest) ProtoMessage() {}

func (x *CoordinatorEnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorEnrollRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorEnrollRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{23}
}

func (x *CoordinatorEnrollRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CoordinatorEnrollRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CoordinatorEnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provisioned   bool                   `protobuf:"varint,1,opt,name=provisioned,proto3" json:"provisioned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorEnrollResponse) Reset() {
	*x = CoordinatorEnrollResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorEnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorEnrollResponse) ProtoMessage() {}

func (x *CoordinatorEnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorEnrollResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorEnrollResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{24}
}

func (x *CoordinatorEnrollResponse) GetProvisioned() bool {
	if x != nil {
		return x.Provisioned
	}
	return false
}

// LocalError describes an error returned by the local IPC service.
type LocalError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable error code (e.g. NOT_FOUND, INVALID_REQUEST, INTERNAL).
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalError) Reset() {
	*x = LocalError{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalError) ProtoMessage() {}

func (x *LocalError) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalError.ProtoReflect.Descriptor instead.
func (*LocalError) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{25}
}

func (x *LocalError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LocalError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LocalRequest is the transport envelope for a request over the local IPC
// channel. The kind of request is determined by which payload field is set.
type LocalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LocalRequest_Import
	//	*LocalRequest_Stat
	//	*LocalRequest_Verify
	//	*LocalRequest_Status
	//	*LocalRequest_ListTransfers
	//	*LocalRequest_CancelTransfer
	//	*LocalRequest_ListLocalFiles
	//	*LocalRequest_MutateLocalFile
	//	*LocalRequest_Export
	//	*LocalRequest_CoordinatorEnroll
	Payload       isLocalRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalRequest) Reset() {
	*x = LocalRequest{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRequest) ProtoMessage() {}

func (x *LocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRequest.ProtoReflect.Descriptor instead.
func (*LocalRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{26}
}

func (x *LocalRequest) GetPayload() isLocalRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LocalRequest) GetImport() *ImportRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_Import); ok {
			return x.Import
		}
	}
	return nil
}

func (x *LocalRequest) GetStat() *StatRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *LocalRequest) GetVerify() *VerifyRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_Verify); ok {
			return x.Verify
		}
	}
	return nil
}

func (x *LocalRequest) GetStatus() *StatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *LocalRequest) GetListTransfers() *ListTransfersRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_ListTransfers); ok {
			return x.ListTransfers
		}
	}
	return nil
}

func (x *LocalRequest) GetCancelTransfer() *CancelTransferRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_CancelTransfer); ok {
			return x.CancelTransfer
		}
	}
	return nil
}

func (x *LocalRequest) GetListLocalFiles() *ListLocalFilesRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_ListLocalFiles); ok {
			return x.ListLocalFiles
		}
	}
	return nil
}

func (x *LocalRequest) GetMutateLocalFile() *MutateLocalFileRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_MutateLocalFile); ok {
			return x.MutateLocalFile
		}
	}
	return nil
}

func (x *LocalRequest) GetExport() *ExportRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_Export); ok {
			return x.Export
		}
	}
	return nil
}

func (x *LocalRequest) GetCoordinatorEnroll() *CoordinatorEnrollRequest {
	if x != nil {
		if x, ok := x.Payload.(*LocalRequest_CoordinatorEnroll); ok {
			return x.CoordinatorEnroll
		}
	}
	return nil
}

type isLocalRequest_Payload interface {
	isLocalRequest_Payload()
}

type LocalRequest_Import struct {
	Import *ImportRequest `protobuf:"bytes,1,opt,name=import,proto3,oneof"`
}

type LocalRequest_Stat struct {
	Stat *StatRequest `protobuf:"bytes,2,opt,name=stat,proto3,oneof"`
}

type LocalRequest_Verify struct {
	Verify *VerifyRequest `protobuf:"bytes,3,opt,name=verify,proto3,oneof"`
}

type LocalRequest_Status struct {
	Status *StatusRequest `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type LocalRequest_ListTransfers struct {
	ListTransfers *ListTransfersRequest `protobuf:"bytes,5,opt,name=list_transfers,json=listTransfers,proto3,oneof"`
}

type LocalRequest_CancelTransfer struct {
	CancelTransfer *CancelTransferRequest `protobuf:"bytes,6,opt,name=cancel_transfer,json=cancelTransfer,proto3,oneof"`
}

type LocalRequest_ListLocalFiles struct {
	ListLocalFiles *ListLocalFilesRequest `protobuf:"bytes,7,opt,name=list_local_files,json=listLocalFiles,proto3,oneof"`
}

type LocalRequest_MutateLocalFile struct {
	MutateLocalFile *MutateLocalFileRequest `protobuf:"bytes,8,opt,name=mutate_local_file,json=mutateLocalFile,proto3,oneof"`
}

type LocalRequest_Export struct {
	Export *ExportRequest `protobuf:"bytes,9,opt,name=export,proto3,oneof"`
}

type LocalRequest_CoordinatorEnroll struct {
	CoordinatorEnroll *CoordinatorEnrollRequest `protobuf:"bytes,10,opt,name=coordinator_enroll,json=coordinatorEnroll,proto3,oneof"`
}

func (*LocalRequest_Import) isLocalRequest_Payload() {}

func (*LocalRequest_Stat) isLocalRequest_Payload() {}

func (*LocalRequest_Verify) isLocalRequest_Payload() {}

func (*LocalRequest_Status) isLocalRequest_Payload() {}

func (*LocalRequest_ListTransfers) isLocalRequest_Payload() {}

func (*LocalRequest_CancelTransfer) isLocalRequest_Payload() {}

func (*LocalRequest_ListLocalFiles) isLocalRequest_Payload() {}

func (*LocalRequest_MutateLocalFile) isLocalRequest_Payload() {}

func (*LocalRequest_Export) isLocalRequest_Payload() {}

func (*LocalRequest_CoordinatorEnroll) isLocalRequest_Payload() {}

// LocalResponse is the transport envelope for a response over the local IPC
// channel. Exactly one of the payload fields is set; error carries failures.
type LocalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LocalResponse_Import
	//	*LocalResponse_Stat
	//	*LocalResponse_Verify
	//	*LocalResponse_Status
	//	*LocalResponse_ListTransfers
	//	*LocalResponse_CancelTransfer
	//	*LocalResponse_Error
	//	*LocalResponse_ListLocalFiles
	//	*LocalResponse_MutateLocalFile
	//	*LocalResponse_Export
	//	*LocalResponse_CoordinatorEnroll
	Payload       isLocalResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalResponse) Reset() {
	*x = LocalResponse{}
	mi := &file_sharedisk_v1_local_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalResponse) ProtoMessage() {}

func (x *LocalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_local_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalResponse.ProtoReflect.Descriptor instead.
func (*LocalResponse) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_local_proto_rawDescGZIP(), []int{27}
}

func (x *LocalResponse) GetPayload() isLocalResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LocalResponse) GetImport() *ImportResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_Import); ok {
			return x.Import
		}
	}
	return nil
}

func (x *LocalResponse) GetStat() *StatResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *LocalResponse) GetVerify() *VerifyResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_Verify); ok {
			return x.Verify
		}
	}
	return nil
}

func (x *LocalResponse) GetStatus() *StatusResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *LocalResponse) GetListTransfers() *ListTransfersResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_ListTransfers); ok {
			return x.ListTransfers
		}
	}
	return nil
}

func (x *LocalResponse) GetCancelTransfer() *CancelTransferResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_CancelTransfer); ok {
			return x.CancelTransfer
		}
	}
	return nil
}

func (x *LocalResponse) GetError() *LocalError {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *LocalResponse) GetListLocalFiles() *ListLocalFilesResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_ListLocalFiles); ok {
			return x.ListLocalFiles
		}
	}
	return nil
}

func (x *LocalResponse) GetMutateLocalFile() *MutateLocalFileResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_MutateLocalFile); ok {
			return x.MutateLocalFile
		}
	}
	return nil
}

func (x *LocalResponse) GetExport() *ExportResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_Export); ok {
			return x.Export
		}
	}
	return nil
}

func (x *LocalResponse) GetCoordinatorEnroll() *CoordinatorEnrollResponse {
	if x != nil {
		if x, ok := x.Payload.(*LocalResponse_CoordinatorEnroll); ok {
			return x.CoordinatorEnroll
		}
	}
	return nil
}

type isLocalResponse_Payload interface {
	isLocalResponse_Payload()
}

type LocalResponse_Import struct {
	Import *ImportResponse `protobuf:"bytes,1,opt,name=import,proto3,oneof"`
}

type LocalResponse_Stat struct {
	Stat *StatResponse `protobuf:"bytes,2,opt,name=stat,proto3,oneof"`
}

type LocalResponse_Verify struct {
	Verify *VerifyResponse `protobuf:"bytes,3,opt,name=verify,proto3,oneof"`
}

type LocalResponse_Status struct {
	Status *StatusResponse `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type LocalResponse_ListTransfers struct {
	ListTransfers *ListTransfersResponse `protobuf:"bytes,5,opt,name=list_transfers,json=listTransfers,proto3,oneof"`
}

type LocalResponse_CancelTransfer struct {
	CancelTransfer *CancelTransferResponse `protobuf:"bytes,6,opt,name=cancel_transfer,json=cancelTransfer,proto3,oneof"`
}

type LocalResponse_Error struct {
	Error *LocalError `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type LocalResponse_ListLocalFiles struct {
	ListLocalFiles *ListLocalFilesResponse `protobuf:"bytes,8,opt,name=list_local_files,json=listLocalFiles,proto3,oneof"`
}

type LocalResponse_MutateLocalFile struct {
	MutateLocalFile *MutateLocalFileResponse `protobuf:"bytes,9,opt,name=mutate_local_file,json=mutateLocalFile,proto3,oneof"`
}

type LocalResponse_Export struct {
	Export *ExportResponse `protobuf:"bytes,10,opt,name=export,proto3,oneof"`
}

type LocalResponse_CoordinatorEnroll struct {
	CoordinatorEnroll *CoordinatorEnrollResponse `protobuf:"bytes,11,opt,name=coordinator_enroll,json=coordinatorEnroll,proto3,oneof"`
}

func (*LocalResponse_Import) isLocalResponse_Payload() {}

func (*LocalResponse_Stat) isLocalResponse_Payload() {}

func (*LocalResponse_Verify) isLocalResponse_Payload() {}

func (*LocalResponse_Status) isLocalResponse_Payload() {}

func (*LocalResponse_ListTransfers) isLocalResponse_Payload() {}

func (*LocalResponse_CancelTransfer) isLocalResponse_Payload() {}

func (*LocalResponse_Error) isLocalResponse_Payload() {}

func (*LocalResponse_ListLocalFiles) isLocalResponse_Payload() {}

func (*LocalResponse_MutateLocalFile) isLocalResponse_Payload() {}

func (*LocalResponse_Export) isLocalResponse_Payload() {}

func (*LocalResponse_CoordinatorEnroll) isLocalResponse_Payload() {}

var File_sharedisk_v1_local_proto protoreflect.FileDescriptor

const file_sharedisk_v1_local_proto_rawDesc = "" +
	"\n" +
	"\x18sharedisk/v1/local.proto\x12\fsharedisk.v1\"a\n" +
	"\rImportRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x86\x01\n" +
	"\x0eImportResponse\x12\"\n" +
	"\rfile_entry_id\x18\x01 \x01(\tR\vfileEntryId\x12$\n" +
	"\x0efile_object_id\x18\x02 \x01(\tR\ffileObjectId\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\"-\n" +
	"\vStatRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"\xa2\x01\n" +
	"\fStatResponse\x12-\n" +
	"\x05entry\x18\x01 \x01(\v2\x17.sharedisk.v1.FileEntryR\x05entry\x120\n" +
	"\x06object\x18\x02 \x01(\v2\x18.sharedisk.v1.FileObjectR\x06object\x121\n" +
	"\breplicas\x18\x03 \x03(\v2\x15.sharedisk.v1.ReplicaR\breplicas\"\x83\x02\n" +
	"\tFileEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tobject_id\x18\x04 \x01(\tR\bobjectId\x12(\n" +
	"\x10origin_device_id\x18\x05 \x01(\tR\x0eoriginDeviceId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xb4\x01\n" +
	"\n" +
	"FileObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\rR\tchunkSize\x12\x1f\n" +
	"\vchunk_count\x18\x06 \x01(\rR\n" +
	"chunkCount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xd9\x01\n" +
	"\aReplica\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x1f\n" +
	"\vverified_at\x18\x06 \x01(\tR\n" +
	"verifiedAt\x12\x1f\n" +
	"\vreported_at\x18\a \x01(\tR\n" +
	"reportedAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\",\n" +
	"\rVerifyRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"a\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\ractual_sha256\x18\x02 \x01(\fR\factualSha256\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0f\n" +
	"\rStatusRequest\"\xac\x02\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\fstorage_root\x18\x03 \x01(\tR\vstorageRoot\x12!\n" +
	"\fobject_count\x18\x04 \x01(\x03R\vobjectCount\x12!\n" +
	"\fstorage_used\x18\x05 \x01(\x04R\vstorageUsed\x12+\n" +
	"\x11storage_available\x18\x06 \x01(\x04R\x10storageAvailable\x12)\n" +
	"\x10active_transfers\x18\a \x01(\x05R\x0factiveTransfers\x12\"\n" +
	"\rlast_sync_seq\x18\b \x01(\x03R\vlastSyncSeq\"\\\n" +
	"\x14ListTransfersRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"n\n" +
	"\x15ListTransfersResponse\x124\n" +
	"\ttransfers\x18\x01 \x03(\v2\x16.sharedisk.v1.TransferR\ttransfers\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xdf\x02\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12(\n" +
	"\x10target_device_id\x18\x03 \x01(\tR\x0etargetDeviceId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vlease_owner\x18\a \x01(\tR\n" +
	"leaseOwner\x12\x1f\n" +
	"\vlease_until\x18\b \x01(\tR\n" +
	"leaseUntil\x12\x18\n" +
	"\aattempt\x18\t \x01(\x05R\aattempt\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"8\n" +
	"\x15CancelTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"J\n" +
	"\x16CancelTransferResponse\x12\x1a\n" +
	"\bcanceled\x18\x01 \x01(\bR\bcanceled\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xcd\x01\n" +
	"\x0fLocalFileRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\a \x01(\tR\tdeletedAt\x12\x1f\n" +
	"\vpurge_after\x18\b \x01(\tR\n" +
	"purgeAfter\"-\n" +
	"\x15ListLocalFilesRequest\x12\x14\n" +
	"\x05trash\x18\x01 \x01(\bR\x05trash\"M\n" +
	"\x16ListLocalFilesResponse\x123\n" +
	"\x05files\x18\x01 \x03(\v2\x1d.sharedisk.v1.LocalFileRecordR\x05files\"]\n" +
	"\x16MutateLocalFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"L\n" +
	"\x17MutateLocalFileResponse\x121\n" +
	"\x04file\x18\x01 \x01(\v2\x1d.sharedisk.v1.LocalFileRecordR\x04file\"S\n" +
	"\rExportRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\"g\n" +
	"\x0eExportResponse\x12)\n" +
	"\x10destination_path\x18\x01 \x01(\tR\x0fdestinationPath\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"P\n" +
	"\x18CoordinatorEnrollRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"=\n" +
	"\x19CoordinatorEnrollResponse\x12 \n" +
	"\vprovisioned\x18\x01 \x01(\bR\vprovisioned\":\n" +
	"\n" +
	"LocalError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc1\x05\n" +
	"\fLocalRequest\x125\n" +
	"\x06import\x18\x01 \x01(\v2\x1b.sharedisk.v1.ImportRequestH\x00R\x06import\x12/\n" +
	"\x04stat\x18\x02 \x01(\v2\x19.sharedisk.v1.StatRequestH\x00R\x04stat\x125\n" +
	"\x06verify\x18\x03 \x01(\v2\x1b.sharedisk.v1.VerifyRequestH\x00R\x06verify\x125\n" +
	"\x06status\x18\x04 \x01(\v2\x1b.sharedisk.v1.StatusRequestH\x00R\x06status\x12K\n" +
	"\x0elist_transfers\x18\x05 \x01(\v2\".sharedisk.v1.ListTransfersRequestH\x00R\rlistTransfers\x12N\n" +
	"\x0fcancel_transfer\x18\x06 \x01(\v2#.sharedisk.v1.CancelTransferRequestH\x00R\x0ecancelTransfer\x12O\n" +
	"\x10list_local_files\x18\a \x01(\v2#.sharedisk.v1.ListLocalFilesRequestH\x00R\x0elistLocalFiles\x12R\n" +
	"\x11mutate_local_file\x18\b \x01(\v2$.sharedisk.v1.MutateLocalFileRequestH\x00R\x0fmutateLocalFile\x125\n" +
	"\x06export\x18\t \x01(\v2\x1b.sharedisk.v1.ExportRequestH\x00R\x06export\x12W\n" +
	"\x12coordinator_enroll\x18\n" +
	" \x01(\v2&.sharedisk.v1.CoordinatorEnrollRequestH\x00R\x11coordinatorEnrollB\t\n" +
	"\apayload\"\xfe\x05\n" +
	"\rLocalResponse\x126\n" +
	"\x06import\x18\x01 \x01(\v2\x1c.sharedisk.v1.ImportResponseH\x00R\x06import\x120\n" +
	"\x04stat\x18\x02 \x01(\v2\x1a.sharedisk.v1.StatResponseH\x00R\x04stat\x126\n" +
	"\x06verify\x18\x03 \x01(\v2\x1c.sharedisk.v1.VerifyResponseH\x00R\x06verify\x126\n" +
	"\x06status\x18\x04 \x01(\v2\x1c.sharedisk.v1.StatusResponseH\x00R\x06status\x12L\n" +
	"\x0elist_transfers\x18\x05 \x01(\v2#.sharedisk.v1.ListTransfersResponseH\x00R\rlistTransfers\x12O\n" +
	"\x0fcancel_transfer\x18\x06 \x01(\v2$.sharedisk.v1.CancelTransferResponseH\x00R\x0ecancelTransfer\x120\n" +
	"\x05error\x18\a \x01(\v2\x18.sharedisk.v1.LocalErrorH\x00R\x05error\x12P\n" +
	"\x10list_local_files\x18\b \x01(\v2$.sharedisk.v1.ListLocalFilesResponseH\x00R\x0elistLocalFiles\x12S\n" +
	"\x11mutate_local_file\x18\t \x01(\v2%.sharedisk.v1.MutateLocalFileResponseH\x00R\x0fmutateLocalFile\x126\n" +
	"\x06export\x18\n" +
	" \x01(\v2\x1c.sharedisk.v1.ExportResponseH\x00R\x06export\x12X\n" +
	"\x12coordinator_enroll\x18\v \x01(\v2'.sharedisk.v1.CoordinatorEnrollResponseH\x00R\x11coordinatorEnrollB\t\n" +
	"\apayload2\x90\x05\n" +
	"\fLocalService\x12C\n" +
	"\x06Import\x12\x1b.sharedisk.v1.ImportRequest\x1a\x1c.sharedisk.v1.ImportResponse\x12=\n" +
	"\x04Stat\x12\x19.sharedisk.v1.StatRequest\x1a\x1a.sharedisk.v1.StatResponse\x12C\n" +
	"\x06Verify\x12\x1b.sharedisk.v1.VerifyRequest\x1a\x1c.sharedisk.v1.VerifyResponse\x12C\n" +
	"\x06Status\x12\x1b.sharedisk.v1.StatusRequest\x1a\x1c.sharedisk.v1.StatusResponse\x12X\n" +
	"\rListTransfers\x12\".sharedisk.v1.ListTransfersRequest\x1a#.sharedisk.v1.ListTransfersResponse\x12[\n" +
	"\x0eCancelTransfer\x12#.sharedisk.v1.CancelTransferRequest\x1a$.sharedisk.v1.CancelTransferResponse\x12[\n" +
	"\x0eListLocalFiles\x12#.sharedisk.v1.ListLocalFilesRequest\x1a$.sharedisk.v1.ListLocalFilesResponse\x12^\n" +
	"\x0fMutateLocalFile\x12$.sharedisk.v1.MutateLocalFileRequest\x1a%.sharedisk.v1.MutateLocalFileResponseBKZIgithub.com/share-disk/share-disk/contracts/proto/sharedisk/v1;sharediskv1b\x06proto3"

var (
	file_sharedisk_v1_local_proto_rawDescOnce sync.Once
	file_sharedisk_v1_local_proto_rawDescData []byte
)

func file_sharedisk_v1_local_proto_rawDescGZIP() []byte {
	file_sharedisk_v1_local_proto_rawDescOnce.Do(func() {
		file_sharedisk_v1_local_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sharedisk_v1_local_proto_rawDesc), len(file_sharedisk_v1_local_proto_rawDesc)))
	})
	return file_sharedisk_v1_local_proto_rawDescData
}

var file_sharedisk_v1_local_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_sharedisk_v1_local_proto_goTypes = []any{
	(*ImportRequest)(nil),             // 0: sharedisk.v1.ImportRequest
	(*ImportResponse)(nil),            // 1: sharedisk.v1.ImportResponse
	(*StatRequest)(nil),               // 2: sharedisk.v1.StatRequest
	(*StatResponse)(nil),              // 3: sharedisk.v1.StatResponse
	(*FileEntry)(nil),                 // 4: sharedisk.v1.FileEntry
	(*FileObject)(nil),                // 5: sharedisk.v1.FileObject
	(*Replica)(nil),                   // 6: sharedisk.v1.Replica
	(*VerifyRequest)(nil),             // 7: sharedisk.v1.VerifyRequest
	(*VerifyResponse)(nil),            // 8: sharedisk.v1.VerifyResponse
	(*StatusRequest)(nil),             // 9: sharedisk.v1.StatusRequest
	(*StatusResponse)(nil),            // 10: sharedisk.v1.StatusResponse
	(*ListTransfersRequest)(nil),      // 11: sharedisk.v1.ListTransfersRequest
	(*ListTransfersResponse)(nil),     // 12: sharedisk.v1.ListTransfersResponse
	(*Transfer)(nil),                  // 13: sharedisk.v1.Transfer
	(*CancelTransferRequest)(nil),     // 14: sharedisk.v1.CancelTransferRequest
	(*CancelTransferResponse)(nil),    // 15: sharedisk.v1.CancelTransferResponse
	(*LocalFileRecord)(nil),           // 16: sharedisk.v1.LocalFileRecord
	(*ListLocalFilesRequest)(nil),     // 17: sharedisk.v1.ListLocalFilesRequest
	(*ListLocalFilesResponse)(nil),    // 18: sharedisk.v1.ListLocalFilesResponse
	(*MutateLocalFileRequest)(nil),    // 19: sharedisk.v1.MutateLocalFileRequest
	(*MutateLocalFileResponse)(nil),   // 20: sharedisk.v1.MutateLocalFileResponse
	(*ExportRequest)(nil),             // 21: sharedisk.v1.ExportRequest
	(*ExportResponse)(nil),            // 22: sharedisk.v1.ExportResponse
	(*CoordinatorEnrollRequest)(nil),  // 23: sharedisk.v1.CoordinatorEnrollRequest
	(*CoordinatorEnrollResponse)(nil), // 24: sharedisk.v1.CoordinatorEnrollResponse
	(*LocalError)(nil),                // 25: sharedisk.v1.LocalError
	(*LocalRequest)(nil),              // 26: sharedisk.v1.LocalRequest
	(*LocalResponse)(nil),             // 27: sharedisk.v1.LocalResponse
}
var file_sharedisk_v1_local_proto_depIdxs = []int32{
	4,  // 0: sharedisk.v1.StatResponse.entry:type_name -> sharedisk.v1.FileEntry
	5,  // 1: sharedisk.v1.StatResponse.object:type_name -> sharedisk.v1.FileObject
	6,  // 2: sharedisk.v1.StatResponse.replicas:type_name -> sharedisk.v1.Replica
	13, // 3: sharedisk.v1.ListTransfersResponse.transfers:type_name -> sharedisk.v1.Transfer
	16, // 4: sharedisk.v1.ListLocalFilesResponse.files:type_name -> sharedisk.v1.LocalFileRecord
	16, // 5: sharedisk.v1.MutateLocalFileResponse.file:type_name -> sharedisk.v1.LocalFileRecord
	0,  // 6: sharedisk.v1.LocalRequest.import:type_name -> sharedisk.v1.ImportRequest
	2,  // 7: sharedisk.v1.LocalRequest.stat:type_name -> sharedisk.v1.StatRequest
	7,  // 8: sharedisk.v1.LocalRequest.verify:type_name -> sharedisk.v1.VerifyRequest
	9,  // 9: sharedisk.v1.LocalRequest.status:type_name -> sharedisk.v1.StatusRequest
	11, // 10: sharedisk.v1.LocalRequest.list_transfers:type_name -> sharedisk.v1.ListTransfersRequest
	14, // 11: sharedisk.v1.LocalRequest.cancel_transfer:type_name -> sharedisk.v1.CancelTransferRequest
	17, // 12: sharedisk.v1.LocalRequest.list_local_files:type_name -> sharedisk.v1.ListLocalFilesRequest
	19, // 13: sharedisk.v1.LocalRequest.mutate_local_file:type_name -> sharedisk.v1.MutateLocalFileRequest
	21, // 14: sharedisk.v1.LocalRequest.export:type_name -> sharedisk.v1.ExportRequest
	23, // 15: sharedisk.v1.LocalRequest.coordinator_enroll:type_name -> sharedisk.v1.CoordinatorEnrollRequest
	1,  // 16: sharedisk.v1.LocalResponse.import:type_name -> sharedisk.v1.ImportResponse
	3,  // 17: sharedisk.v1.LocalResponse.stat:type_name -> sharedisk.v1.StatResponse
	8,  // 18: sharedisk.v1.LocalResponse.verify:type_name -> sharedisk.v1.VerifyResponse
	10, // 19: sharedisk.v1.LocalResponse.status:type_name -> sharedisk.v1.StatusResponse
	12, // 20: sharedisk.v1.LocalResponse.list_transfers:type_name -> sharedisk.v1.ListTransfersResponse
	15, // 21: sharedisk.v1.LocalResponse.cancel_transfer:type_name -> sharedisk.v1.CancelTransferResponse
	25, // 22: sharedisk.v1.LocalResponse.error:type_name -> sharedisk.v1.LocalError
	18, // 23: sharedisk.v1.LocalResponse.list_local_files:type_name -> sharedisk.v1.ListLocalFilesResponse
	20, // 24: sharedisk.v1.LocalResponse.mutate_local_file:type_name -> sharedisk.v1.MutateLocalFileResponse
	22, // 25: sharedisk.v1.LocalResponse.export:type_name -> sharedisk.v1.ExportResponse
	24, // 26: sharedisk.v1.LocalResponse.coordinator_enroll:type_name -> sharedisk.v1.CoordinatorEnrollResponse
	0,  // 27: sharedisk.v1.LocalService.Import:input_type -> sharedisk.v1.ImportRequest
	2,  // 28: sharedisk.v1.LocalService.Stat:input_type -> sharedisk.v1.StatRequest
	7,  // 29: sharedisk.v1.LocalService.Verify:input_type -> sharedisk.v1.VerifyRequest
	9,  // 30: sharedisk.v1.LocalService.Status:input_type -> sharedisk.v1.StatusRequest
	11, // 31: sharedisk.v1.LocalService.ListTransfers:input_type -> sharedisk.v1.ListTransfersRequest
	14, // 32: sharedisk.v1.LocalService.CancelTransfer:input_type -> sharedisk.v1.CancelTransferRequest
	17, // 33: sharedisk.v1.LocalService.ListLocalFiles:input_type -> sharedisk.v1.ListLocalFilesRequest
	19, // 34: sharedisk.v1.LocalService.MutateLocalFile:input_type -> sharedisk.v1.MutateLocalFileRequest
	1,  // 35: sharedisk.v1.LocalService.Import:output_type -> sharedisk.v1.ImportResponse
	3,  // 36: sharedisk.v1.LocalService.Stat:output_type -> sharedisk.v1.StatResponse
	8,  // 37: sharedisk.v1.LocalService.Verify:output_type -> sharedisk.v1.VerifyResponse
	10, // 38: sharedisk.v1.LocalService.Status:output_type -> sharedisk.v1.StatusResponse
	12, // 39: sharedisk.v1.LocalService.ListTransfers:output_type -> sharedisk.v1.ListTransfersResponse
	15, // 40: sharedisk.v1.LocalService.CancelTransfer:output_type -> sharedisk.v1.CancelTransferResponse
	18, // 41: sharedisk.v1.LocalService.ListLocalFiles:output_type -> sharedisk.v1.ListLocalFilesResponse
	20, // 42: sharedisk.v1.LocalService.MutateLocalFile:output_type -> sharedisk.v1.MutateLocalFileResponse
	35, // [35:43] is the sub-list for method output_type
	27, // [27:35] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_sharedisk_v1_local_proto_init() }
func file_sharedisk_v1_local_proto_init() {
	if File_sharedisk_v1_local_proto != nil {
		return
	}
	file_sharedisk_v1_local_proto_msgTypes[26].OneofWrappers = []any{
		(*LocalRequest_Import)(nil),
		(*LocalRequest_Stat)(nil),
		(*LocalRequest_Verify)(nil),
		(*LocalRequest_Status)(nil),
		(*LocalRequest_ListTransfers)(nil),
		(*LocalRequest_CancelTransfer)(nil),
		(*LocalRequest_ListLocalFiles)(nil),
		(*LocalRequest_MutateLocalFile)(nil),
		(*LocalRequest_Export)(nil),
		(*LocalRequest_CoordinatorEnroll)(nil),
	}
	file_sharedisk_v1_local_proto_msgTypes[27].OneofWrappers = []any{
		(*LocalResponse_Import)(nil),
		(*LocalResponse_Stat)(nil),
		(*LocalResponse_Verify)(nil),
		(*LocalResponse_Status)(nil),
		(*LocalResponse_ListTransfers)(nil),
		(*LocalResponse_CancelTransfer)(nil),
		(*LocalResponse_Error)(nil),
		(*LocalResponse_ListLocalFiles)(nil),
		(*LocalResponse_MutateLocalFile)(nil),
		(*LocalResponse_Export)(nil),
		(*LocalResponse_CoordinatorEnroll)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sharedisk_v1_local_proto_rawDesc), len(file_sharedisk_v1_local_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sharedisk_v1_local_proto_goTypes,
		DependencyIndexes: file_sharedisk_v1_local_proto_depIdxs,
		MessageInfos:      file_sharedisk_v1_local_proto_msgTypes,
	}.Build()
	File_sharedisk_v1_local_proto = out.File
	file_sharedisk_v1_local_proto_goTypes = nil
	file_sharedisk_v1_local_proto_depIdxs = nil
}
