// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: sharedisk/v1/transfer.proto

package sharediskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RejectReason enumerates possible rejection reasons.
type RejectReason int32

const (
	RejectReason_REJECT_REASON_UNSPECIFIED      RejectReason = 0
	RejectReason_REJECT_REASON_INVALID_TICKET   RejectReason = 1
	RejectReason_REJECT_REASON_TICKET_EXPIRED   RejectReason = 2
	RejectReason_REJECT_REASON_INVALID_PEER     RejectReason = 3
	RejectReason_REJECT_REASON_OBJECT_NOT_FOUND RejectReason = 4
	RejectReason_REJECT_REASON_INVALID_HASH     RejectReason = 5
	RejectReason_REJECT_REASON_RATE_LIMITED     RejectReason = 6
	RejectReason_REJECT_REASON_INTERNAL_ERROR   RejectReason = 7
)

// Enum value maps for RejectReason.
var (
	RejectReason_name = map[int32]string{
		0: "REJECT_REASON_UNSPECIFIED",
		1: "REJECT_REASON_INVALID_TICKET",
		2: "REJECT_REASON_TICKET_EXPIRED",
		3: "REJECT_REASON_INVALID_PEER",
		4: "REJECT_REASON_OBJECT_NOT_FOUND",
		5: "REJECT_REASON_INVALID_HASH",
		6: "REJECT_REASON_RATE_LIMITED",
		7: "REJECT_REASON_INTERNAL_ERROR",
	}
	RejectReason_value = map[string]int32{
		"REJECT_REASON_UNSPECIFIED":      0,
		"REJECT_REASON_INVALID_TICKET":   1,
		"REJECT_REASON_TICKET_EXPIRED":   2,
		"REJECT_REASON_INVALID_PEER":     3,
		"REJECT_REASON_OBJECT_NOT_FOUND": 4,
		"REJECT_REASON_INVALID_HASH":     5,
		"REJECT_REASON_RATE_LIMITED":     6,
		"REJECT_REASON_INTERNAL_ERROR":   7,
	}
)

func (x RejectReason) Enum() *RejectReason {
	p := new(RejectReason)
	*p = x
	return p
}

func (x RejectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RejectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_sharedisk_v1_transfer_proto_enumTypes[0].Descriptor()
}

func (RejectReason) Type() protoreflect.EnumType {
	return &file_sharedisk_v1_transfer_proto_enumTypes[0]
}

func (x RejectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RejectReason.Descriptor instead.
func (RejectReason) EnumDescriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{0}
}

// TransferStatus enumerates possible transfer completion statuses.
type TransferStatus int32

const (
	TransferStatus_TRANSFER_STATUS_UNSPECIFIED      TransferStatus = 0
	TransferStatus_TRANSFER_STATUS_COMPLETED        TransferStatus = 1
	TransferStatus_TRANSFER_STATUS_CANCELED         TransferStatus = 2
	TransferStatus_TRANSFER_STATUS_FAILED           TransferStatus = 3
	TransferStatus_TRANSFER_STATUS_SOURCE_EXHAUSTED TransferStatus = 4
)

// Enum value maps for TransferStatus.
var (
	TransferStatus_name = map[int32]string{
		0: "TRANSFER_STATUS_UNSPECIFIED",
		1: "TRANSFER_STATUS_COMPLETED",
		2: "TRANSFER_STATUS_CANCELED",
		3: "TRANSFER_STATUS_FAILED",
		4: "TRANSFER_STATUS_SOURCE_EXHAUSTED",
	}
	TransferStatus_value = map[string]int32{
		"TRANSFER_STATUS_UNSPECIFIED":      0,
		"TRANSFER_STATUS_COMPLETED":        1,
		"TRANSFER_STATUS_CANCELED":         2,
		"TRANSFER_STATUS_FAILED":           3,
		"TRANSFER_STATUS_SOURCE_EXHAUSTED": 4,
	}
)

func (x TransferStatus) Enum() *TransferStatus {
	p := new(TransferStatus)
	*p = x
	return p
}

func (x TransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sharedisk_v1_transfer_proto_enumTypes[1].Descriptor()
}

func (TransferStatus) Type() protoreflect.EnumType {
	return &file_sharedisk_v1_transfer_proto_enumTypes[1]
}

func (x TransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatus.Descriptor instead.
func (TransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{1}
}

// TransferOpen is sent by the target device to initiate a transfer.
type TransferOpen struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version for compatibility checking.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Task ID from the control server.
	TaskId string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Transfer ticket signed by the control server.
	Ticket []byte `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// SHA-256 hash of the object to transfer.
	ObjectHash []byte `protobuf:"bytes,4,opt,name=object_hash,json=objectHash,proto3" json:"object_hash,omitempty"`
	// Requested chunk indices (empty means all chunks).
	RequestedChunks []uint32 `protobuf:"varint,5,rep,packed,name=requested_chunks,json=requestedChunks,proto3" json:"requested_chunks,omitempty"`
	// Canonical manifest SHA-256 approved by the target's transfer plan.
	ManifestDigest []byte `protobuf:"bytes,6,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferOpen) Reset() {
	*x = TransferOpen{}
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOpen) ProtoMessage() {}

func (x *TransferOpen) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOpen.ProtoReflect.Descriptor instead.
func (*TransferOpen) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *TransferOpen) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *TransferOpen) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TransferOpen) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *TransferOpen) GetObjectHash() []byte {
	if x != nil {
		return x.ObjectHash
	}
	return nil
}

func (x *TransferOpen) GetRequestedChunks() []uint32 {
	if x != nil {
		return x.RequestedChunks
	}
	return nil
}

func (x *TransferOpen) GetManifestDigest() []byte {
	if x != nil {
		return x.ManifestDigest
	}
	return nil
}

// TransferAccept is sent by the source device to accept a transfer request.
type TransferAccept struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk size in bytes.
	ChunkSize uint32 `protobuf:"varint,1,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	// Total object size in bytes.
	TotalSize uint64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Manifest digest for verification.
	ManifestDigest []byte `protobuf:"bytes,3,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	// Available chunk indices (may be subset if source has partial object).
	AvailableChunks []uint32 `protobuf:"varint,4,rep,packed,name=available_chunks,json=availableChunks,proto3" json:"available_chunks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferAccept) Reset() {
	*x = TransferAccept{}
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAccept) ProtoMessage() {}

func (x *TransferAccept) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAccept.ProtoReflect.Descriptor instead.
func (*TransferAccept) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *TransferAccept) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *TransferAccept) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *TransferAccept) GetManifestDigest() []byte {
	if x != nil {
		return x.ManifestDigest
	}
	return nil
}

func (x *TransferAccept) GetAvailableChunks() []uint32 {
	if x != nil {
		return x.AvailableChunks
	}
	return nil
}

// TransferReject is sent by the source device to reject a transfer request.
type TransferReject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reason code for rejection.
	Reason RejectReason `protobuf:"varint,1,opt,name=reason,proto3,enum=sharedisk.v1.RejectReason" json:"reason,omitempty"`
	// Human-readable error message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReject) Reset() {
	*x = TransferReject{}
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReject) ProtoMessage() {}

func (x *TransferReject) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReject.ProtoReflect.Descriptor instead.
func (*TransferReject) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *TransferReject) GetReason() RejectReason {
	if x != nil {
		return x.Reason
	}
	return RejectReason_REJECT_REASON_UNSPECIFIED
}

func (x *TransferReject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ChunkRequest is sent by the target device to request specific chunks.
type ChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk index to request.
	Index         uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// ChunkData is sent by the source device with chunk data.
type ChunkData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk index.
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Byte offset within the object.
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Chunk data bytes.
	Bytes []byte `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// SHA-256 hash of this chunk.
	ChunkHash     []byte `protobuf:"bytes,4,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkData) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkData) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChunkData) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *ChunkData) GetChunkHash() []byte {
	if x != nil {
		return x.ChunkHash
	}
	return nil
}

// ChunkAck is sent by the target device after verifying and persisting a chunk.
type ChunkAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk index that was acknowledged.
	Index         uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkAck) Reset() {
	*x = ChunkAck{}
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkAck) ProtoMessage() {}

func (x *ChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkAck.ProtoReflect.Descriptor instead.
func (*ChunkAck) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *ChunkAck) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// TransferClose is sent by either device to close the transfer.
type TransferClose struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Final status of the transfer.
	Status TransferStatus `protobuf:"varint,1,opt,name=status,proto3,enum=sharedisk.v1.TransferStatus" json:"status,omitempty"`
	// Human-readable message (optional).
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferClose) Reset() {
	*x = TransferClose{}
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferClose) ProtoMessage() {}

func (x *TransferClose) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferClose.ProtoReflect.Descriptor instead.
func (*TransferClose) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *TransferClose) GetStatus() TransferStatus {
	if x != nil {
		return x.Status
	}
	return TransferStatus_TRANSFER_STATUS_UNSPECIFIED
}

func (x *TransferClose) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TransferMessage wraps all possible messages in the transfer protocol.
type TransferMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*TransferMessage_Open
	//	*TransferMessage_Accept
	//	*TransferMessage_Reject
	//	*TransferMessage_ChunkRequest
	//	*TransferMessage_ChunkData
	//	*TransferMessage_ChunkAck
	//	*TransferMessage_Close
	Message       isTransferMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferMessage) Reset() {
	*x = TransferMessage{}
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferMessage) ProtoMessage() {}

func (x *TransferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sharedisk_v1_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferMessage.ProtoReflect.Descriptor instead.
func (*TransferMessage) Descriptor() ([]byte, []int) {
	return file_sharedisk_v1_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *TransferMessage) GetMessage() isTransferMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TransferMessage) GetOpen() *TransferOpen {
	if x != nil {
		if x, ok := x.Message.(*TransferMessage_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *TransferMessage) GetAccept() *TransferAccept {
	if x != nil {
		if x, ok := x.Message.(*TransferMessage_Accept); ok {
			return x.Accept
		}
	}
	return nil
}

func (x *TransferMessage) GetReject() *TransferReject {
	if x != nil {
		if x, ok := x.Message.(*TransferMessage_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

func (x *TransferMessage) GetChunkRequest() *ChunkRequest {
	if x != nil {
		if x, ok := x.Message.(*TransferMessage_ChunkRequest); ok {
			return x.ChunkRequest
		}
	}
	return nil
}

func (x *TransferMessage) GetChunkData() *ChunkData {
	if x != nil {
		if x, ok := x.Message.(*TransferMessage_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

func (x *TransferMessage) GetChunkAck() *ChunkAck {
	if x != nil {
		if x, ok := x.Message.(*TransferMessage_ChunkAck); ok {
			return x.ChunkAck
		}
	}
	return nil
}

func (x *TransferMessage) GetClose() *TransferClose {
	if x != nil {
		if x, ok := x.Message.(*TransferMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isTransferMessage_Message interface {
	isTransferMessage_Message()
}

type TransferMessage_Open struct {
	Open *TransferOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type TransferMessage_Accept struct {
	Accept *TransferAccept `protobuf:"bytes,2,opt,name=accept,proto3,oneof"`
}

type TransferMessage_Reject struct {
	Reject *TransferReject `protobuf:"bytes,3,opt,name=reject,proto3,oneof"`
}

type TransferMessage_ChunkRequest struct {
	ChunkRequest *ChunkRequest `protobuf:"bytes,4,opt,name=chunk_request,json=chunkRequest,proto3,oneof"`
}

type TransferMessage_ChunkData struct {
	ChunkData *ChunkData `protobuf:"bytes,5,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

type TransferMessage_ChunkAck struct {
	ChunkAck *ChunkAck `protobuf:"bytes,6,opt,name=chunk_ack,json=chunkAck,proto3,oneof"`
}

type TransferMessage_Close struct {
	Close *TransferClose `protobuf:"bytes,7,opt,name=close,proto3,oneof"`
}

func (*TransferMessage_Open) isTransferMessage_Message() {}

func (*TransferMessage_Accept) isTransferMessage_Message() {}

func (*TransferMessage_Reject) isTransferMessage_Message() {}

func (*TransferMessage_ChunkRequest) isTransferMessage_Message() {}

func (*TransferMessage_ChunkData) isTransferMessage_Message() {}

func (*TransferMessage_ChunkAck) isTransferMessage_Message() {}

func (*TransferMessage_Close) isTransferMessage_Message() {}

var File_sharedisk_v1_transfer_proto protoreflect.FileDescriptor

const file_sharedisk_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1bsharedisk/v1/transfer.proto\x12\fsharedisk.v1\"\xdf\x01\n" +
	"\fTransferOpen\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06ticket\x18\x03 \x01(\fR\x06ticket\x12\x1f\n" +
	"\vobject_hash\x18\x04 \x01(\fR\n" +
	"objectHash\x12)\n" +
	"\x10requested_chunks\x18\x05 \x03(\rR\x0frequestedChunks\x12'\n" +
	"\x0fmanifest_digest\x18\x06 \x01(\fR\x0emanifestDigest\"\xa2\x01\n" +
	"\x0eTransferAccept\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x01 \x01(\rR\tchunkSize\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\x12'\n" +
	"\x0fmanifest_digest\x18\x03 \x01(\fR\x0emanifestDigest\x12)\n" +
	"\x10available_chunks\x18\x04 \x03(\rR\x0favailableChunks\"^\n" +
	"\x0eTransferReject\x122\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1a.sharedisk.v1.RejectReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\fChunkRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\"n\n" +
	"\tChunkData\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\fR\x05bytes\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x04 \x01(\fR\tchunkHash\" \n" +
	"\bChunkAck\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\"_\n" +
	"\rTransferClose\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.sharedisk.v1.TransferStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa7\x03\n" +
	"\x0fTransferMessage\x120\n" +
	"\x04open\x18\x01 \x01(\v2\x1a.sharedisk.v1.TransferOpenH\x00R\x04open\x126\n" +
	"\x06accept\x18\x02 \x01(\v2\x1c.sharedisk.v1.TransferAcceptH\x00R\x06accept\x126\n" +
	"\x06reject\x18\x03 \x01(\v2\x1c.sharedisk.v1.TransferRejectH\x00R\x06reject\x12A\n" +
	"\rchunk_request\x18\x04 \x01(\v2\x1a.sharedisk.v1.ChunkRequestH\x00R\fchunkRequest\x128\n" +
	"\n" +
	"chunk_data\x18\x05 \x01(\v2\x17.sharedisk.v1.ChunkDataH\x00R\tchunkData\x125\n" +
	"\tchunk_ack\x18\x06 \x01(\v2\x16.sharedisk.v1.ChunkAckH\x00R\bchunkAck\x123\n" +
	"\x05close\x18\a \x01(\v2\x1b.sharedisk.v1.TransferCloseH\x00R\x05closeB\t\n" +
	"\amessage*\x97\x02\n" +
	"\fRejectReason\x12\x1d\n" +
	"\x19REJECT_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cREJECT_REASON_INVALID_TICKET\x10\x01\x12 \n" +
	"\x1cREJECT_REASON_TICKET_EXPIRED\x10\x02\x12\x1e\n" +
	"\x1aREJECT_REASON_INVALID_PEER\x10\x03\x12\"\n" +
	"\x1eREJECT_REASON_OBJECT_NOT_FOUND\x10\x04\x12\x1e\n" +
	"\x1aREJECT_REASON_INVALID_HASH\x10\x05\x12\x1e\n" +
	"\x1aREJECT_REASON_RATE_LIMITED\x10\x06\x12 \n" +
	"\x1cREJECT_REASON_INTERNAL_ERROR\x10\a*\xb0\x01\n" +
	"\x0eTransferStatus\x12\x1f\n" +
	"\x1bTRANSFER_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TRANSFER_STATUS_COMPLETED\x10\x01\x12\x1c\n" +
	"\x18TRANSFER_STATUS_CANCELED\x10\x02\x12\x1a\n" +
	"\x16TRANSFER_STATUS_FAILED\x10\x03\x12$\n" +
	" TRANSFER_STATUS_SOURCE_EXHAUSTED\x10\x04BKZIgithub.com/share-disk/share-disk/contracts/proto/sharedisk/v1;sharediskv1b\x06proto3"

var (
	file_sharedisk_v1_transfer_proto_rawDescOnce sync.Once
	file_sharedisk_v1_transfer_proto_rawDescData []byte
)

func file_sharedisk_v1_transfer_proto_rawDescGZIP() []byte {
	file_sharedisk_v1_transfer_proto_rawDescOnce.Do(func() {
		file_sharedisk_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sharedisk_v1_transfer_proto_rawDesc), len(file_sharedisk_v1_transfer_proto_rawDesc)))
	})
	return file_sharedisk_v1_transfer_proto_rawDescData
}

var file_sharedisk_v1_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sharedisk_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sharedisk_v1_transfer_proto_goTypes = []any{
	(RejectReason)(0),       // 0: sharedisk.v1.RejectReason
	(TransferStatus)(0),     // 1: sharedisk.v1.TransferStatus
	(*TransferOpen)(nil),    // 2: sharedisk.v1.TransferOpen
	(*TransferAccept)(nil),  // 3: sharedisk.v1.TransferAccept
	(*TransferReject)(nil),  // 4: sharedisk.v1.TransferReject
	(*ChunkRequest)(nil),    // 5: sharedisk.v1.ChunkRequest
	(*ChunkData)(nil),       // 6: sharedisk.v1.ChunkData
	(*ChunkAck)(nil),        // 7: sharedisk.v1.ChunkAck
	(*TransferClose)(nil),   // 8: sharedisk.v1.TransferClose
	(*TransferMessage)(nil), // 9: sharedisk.v1.TransferMessage
}
var file_sharedisk_v1_transfer_proto_depIdxs = []int32{
	0, // 0: sharedisk.v1.TransferReject.reason:type_name -> sharedisk.v1.RejectReason
	1, // 1: sharedisk.v1.TransferClose.status:type_name -> sharedisk.v1.TransferStatus
	2, // 2: sharedisk.v1.TransferMessage.open:type_name -> sharedisk.v1.TransferOpen
	3, // 3: sharedisk.v1.TransferMessage.accept:type_name -> sharedisk.v1.TransferAccept
	4, // 4: sharedisk.v1.TransferMessage.reject:type_name -> sharedisk.v1.TransferReject
	5, // 5: sharedisk.v1.TransferMessage.chunk_request:type_name -> sharedisk.v1.ChunkRequest
	6, // 6: sharedisk.v1.TransferMessage.chunk_data:type_name -> sharedisk.v1.ChunkData
	7, // 7: sharedisk.v1.TransferMessage.chunk_ack:type_name -> sharedisk.v1.ChunkAck
	8, // 8: sharedisk.v1.TransferMessage.close:type_name -> sharedisk.v1.TransferClose
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_sharedisk_v1_transfer_proto_init() }
func file_sharedisk_v1_transfer_proto_init() {
	if File_sharedisk_v1_transfer_proto != nil {
		return
	}
	file_sharedisk_v1_transfer_proto_msgTypes[7].OneofWrappers = []any{
		(*TransferMessage_Open)(nil),
		(*TransferMessage_Accept)(nil),
		(*TransferMessage_Reject)(nil),
		(*TransferMessage_ChunkRequest)(nil),
		(*TransferMessage_ChunkData)(nil),
		(*TransferMessage_ChunkAck)(nil),
		(*TransferMessage_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sharedisk_v1_transfer_proto_rawDesc), len(file_sharedisk_v1_transfer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sharedisk_v1_transfer_proto_goTypes,
		DependencyIndexes: file_sharedisk_v1_transfer_proto_depIdxs,
		EnumInfos:         file_sharedisk_v1_transfer_proto_enumTypes,
		MessageInfos:      file_sharedisk_v1_transfer_proto_msgTypes,
	}.Build()
	File_sharedisk_v1_transfer_proto = out.File
	file_sharedisk_v1_transfer_proto_goTypes = nil
	file_sharedisk_v1_transfer_proto_depIdxs = nil
}
